# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django_rdkit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdmol', django_rdkit.models.fields.MolField()),
                ('internal_id', models.CharField(db_index=True, max_length=32)),
                ('image', models.TextField()),
                ('mw', models.FloatField(db_index=True)),
                ('sum_formula', models.CharField(db_index=True, max_length=32)),
                ('fingerprint', models.CharField(db_index=True, max_length=1024)),
                ('inchi', models.TextField(db_index=True)),
                ('inchi_key', models.CharField(db_index=True, max_length=27)),
                ('name', models.TextField(db_index=True, null=True)),
                ('smiles', models.TextField(db_index=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
